# train
checkpoint_path: null
act_device: "cuda"
train_device: "cuda"
num_threads: 8
num_games_per_thread: 20

lr: !!float 1e-6
seed: 42
burn_in_frames: 100000
buffer_capacity: 800000
num_epochs: 10000
epoch_len: 1000
sample_batch_size: 512
entropy_ratio: 0.01
clip_eps: 0.2
sync_freq: 50

# eval
num_eval_deals: 50000
num_eval_threads: 8
eval_device: "cuda"

# save
save_dir: "policy_gradient"
top_k : 10
